# Generated by Django 3.2.12 on 2022-03-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(choices=[('Agua', 'Agua'), ('Luz', 'Luz'), ('Gas', 'Gas'), ('Compra', 'Compra'), ('Ocio', 'Ocio'), ('Otros', 'Otros')], max_length=10)),
                ('tipo', models.CharField(choices=[('Individual', 'Individual'), ('Común', 'Común')], max_length=10)),
                ('notas', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
